name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies in Backend
      run: |
        cd backend
        npm install

    - name: Run tests in Backend
      run: |
        cd backend
        npm test
      env:
        CI: true

    - name: Install dependencies in Frontend
      run: |
        cd front
        npm install

    - name: Build and test Frontend
      run: |
        cd front
        CI=false npm run build
        CI=true npm test

