name: Backend CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Spécifie le dossier backend comme répertoire de travail

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # ou la version que vous utilisez

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

